# This workflow will build a Java project with Gradle, create repository tag, and push a new docker image to docker hub
name: Create Tag and Push Image to DockerHub

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  security-events: write
   
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Checkout new changes
        uses: actions/checkout@v2
        with:
          java-version: 1.8
          fetch-depth: 0
      -
        name: Setup GitVersion action
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      -
        name: Execute GitVersion action
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      -
        name: Create tag for GitHub
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GH_TOKEN }}"
          tag: '${{ steps.gitversion.outputs.semver }}'
      -
        name: Grant execute permission for gradlew
        run: chmod +x gradlew
      -
        name: Build Container Image with Jib 
        run: |
          ./gradlew jibDockerBuild \
          --image=chucknelson01/owasp-vulnerableapp:unreleased
          
      - 
        name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

        # Runs Snyk Container analysis 
      - 
        name: Snyk Container
        run: snyk container monitor -d --org=3a74cceb-0952-429e-8eaf-d48989afa944 chucknelson01/owasp-vulnerableapp:unreleased || true

        env:
          # This is where you will need to introduce the Snyk API token created with your Snyk account
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - 
        name: Snyk Container SBOM
        run: snyk container sbom --format=cyclonedx1.6+json -d --org=3a74cceb-0952-429e-8eaf-d48989afa944 

        env:
          # This is where you will need to introduce the Snyk API token created with your Snyk account
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      -
        name: Build with Gradle and Push
        run: |
          ./gradlew jib \
          -Djib.to.image=chucknelson01/owasp-vulnerableapp:unreleased \
          -Djib.to.tags=$GITVERSION_SEMVER
